---
title: "Pêche industrielle en Atlantique Centre-Est - Structure, impact et responsabilité de la pêche distante"
date: today

authors:
  - name: Gaspard Ringunenet
    id: gr
    email: gaspard.ringuenet@umontpellier.fr
    roles: writing
    corresponding: true
    affiliation: Université de Montpellier

abstract: >
  Blabla...

keywords:
  - Marine resources
  - Distant water fishing
  - West Africa
  - Ownership analysis
  - Automatic Identification System (AIS)

bibliography: references.bib

title-block-banner: "#11114e"
title-block-banner-color: "#B31B1B"

number-sections: true
---

# Introduction

Distant water fishing, involving vessels operating outside the Exclusive Economic Zones (EEZs) of their state of origin, has become a pillar of the global fishing industry. Although the practice dates back centuries \[ref\], it has known an outstanding growth after the Second World War, driven by the expansion of industrial fishing fleets from the Global North \[ref\]. The adoption of capacity increasing technology has been described as the main cause for this expansion. Indeed, the increase in competitiveness provides a strong incentive at the individual level, but the resulting overcapacity depletes resources and triggers tensions at the regional scale.

------------------------------------------------------------------------

# Paper outline {.unnumbered}

**Angle**

The main idea is to adapt the ownership analysis developed by [@kinds2025] to a new region. The novelty of our work resides in three aspects:

-   No such ownership analysis has been performed in the FAO area 34.

-   We investigate a large part of the trawling fleet operating in the region. This point is crucial as ownership analyses have focused on tuna fleets in the past [@kinds2025; \@]

Research question: ...

-   Focus on the AIS-apparent fishing effort of the trawling fleet in West Africa (bottom + pelagic).

-   Investigate the spatial distribution of flags using a regionalization approach.

-   Perform a large scale trawlers ownership analysis to assess the extent of foreign interest control over the industrial trawling fleet operating in the region.

-   Investigate spatial extent and time intensity of the apparent fishing effort by foreign-owned vessels.

**Intro plan:**

-   Short intro to distant water fisheries and the dominance of companies from wealthy countries.

-   Explain

Include:
