---
title: "Pêche industrielle en Atlantique Centre-Est - Structure, impact et responsabilité de la pêche distante"
date: today

title-block-banner: "#11114e"
title-block-banner-color: "#B31B1B"

authors:
  - name: Gaspard Ringunenet
    id: gr
    email: gaspard.ringuenet@umontpellier.fr
    roles: writing
    corresponding: true
    affiliation: Université de Montpellier

abstract: >
  Blabla...

keywords:
  - Marine resources
  - Distant water fishing
  - West Africa
  - Ownership analysis
  - Automatic Identification System (AIS)

bibliography: references.bib
---

# Introduction

## Pêche distante : conflits, expansion et domination du nord global

Définie comme le fait de pêcher dans des zones lointaines des eaux domestiques, la pêche distante est un phénomène dont on trouve des exemples jusqu'au XVIe siècle, avec la pêche à la morue en Terre-Neuve. L'avènement des chalutiers à vapeur européens - et notamment britanniques - à la fin du XIXe siècle a marqué le début de son expansion rapide. La forte augmentation de la capacité de pêche a rapidement conduit aux premiers signes de surexploitation. La compétition et les conflits entre les secteurs artisanal et industriel domestiques qui en ont résulté ont poussé les flottes de chalutiers à étendre leur zones d'activités au large et chez les pays voisins [@knauss2005]. La capacité et l'emprise spatiale des flottes de pêche industrielle ont ensuite fortement augmenté durant le XXe siècle [@tickler2018; @swartz2010]. Après 1950, les pays riches subventionnent fortement leur flottes [@sumaila2019], qui s'équipent de nouvelles technologies développées pour la marine de guerre (motorisation, systèmes de positionnement, sonar) [@holm2012], dans le but de répondre à l'augmentation de la demande mondiale en produits de la mer [@watson2015; @swartz2010a]. L'explosion de l'effort de pêche industrielle entraîne rapidement la surexploitation des ressources domestiques, poussant les flottes industrielles vers les tropiques et les ZEE de pays en développement [@swartz2010].

Cette expansion a été à l'origine de nombreux conflits entre pêcheurs domestiques et étrangers. Ceux-ci ont joué un rôle historique dans le développement du droit de la mer et les négociations internationales qui aboutirent en 1982 à l'adoption de la Convention des Nations Unis sur le Droit de la Mer (CNUDM). Les article 56 et 57 de la convention établissent la possibilité pour les pays côtiers de déclarer des zones économiques exclusives (ZEE) s'étendant jusqu'à 200 milles nautiques de la côte [@unitedn1982]. Dans sa ZEE, un État a la responsabilité et le contrôle exclusif de l'exploitation, de la gestion et de la conservation des ressources, en particulier halieutiques. Mettant fin à l'accès libre aux ressources marines, la CNUDM n'est cependant pas conçue comme un frein à la pêche distante. Au contraire, l'article 62 instaure la notion de surplus, enjoignant aux états qui n'exploitent pas pleinement - i.e. au rendement maximum durable (RMD) - leurs ressources halieutiques d'ouvrir leurs ZEE aux flottes de pêche étrangère.

"\[...\] Where the coastal State does not have the capacity to harvest the entire allowable catch, it shall, through agreements or other arrangements \[...\] give other States access to the surplus of the allowable catch \[...\]"

Cette réglementation induit une séparation entre les états détenteurs de ressources (en anglais resource holders), principalement composés de pays en développement disposant d'une capacité de pêche industrielle limitée et dont les eaux sont très productives, et les états chercheurs de ressources (resource seekers), développés et possédant de grandes flottes de pêche distante. Puisque les États chercheurs de ressources possèdent déjà la capacité pour exploiter pleinement leurs stocks, il s'installe alors une certaine dichotomie entre les deux catégories. En conséquence, on observe que les grandes nations de pêche du nord global ont rapidement négocié de nombreux accords pour l'accès à la pêche, en particulier dans les eaux des pays côtiers en développement [@garcia2014; @alder2004; @lemanach2013; @mallory2013].

Les accords de pêche, qui ouvrent les ZEE des pays détenteurs de ressources à la pêche étrangère en échange d'une contrepartie financière, sont l'objet de critiques en raison de leurs impacts socio-économiques et environnementaux sur les pays en développement. Issus de négociations fortement asymétriques, les conditions mêmes des accords sont jugées peu durables et équitables [@belhabib2015; @campling2024]. Les conflits pour l'espace et la ressource avec les secteurs de pêche locaux, et en particulier la petite pêche, sont également fréquents, entraînant la diminution des moyens de subsistance domestiques et l'augmentation du risque d'insécurité alimentaire chez les communautés côtières [@belhabib2020; @okafor-yarwood2022; @spijkers2019; @spijkers2021]. De plus, en ouvrant la pêche aux flottes étrangères dans des pays au capacité de surveillance limités, les accords peuvent contribuer au développement de la pêche illégale, non déclarée et non réglementée (INN), aggravant encore les conséquences pour les communautés côtières [@lemanach2012; @belhabib2020; @seto2017]. A cela s'ajoute la corruption des représentants des pays détenteurs de ressources, dont Stäbler [-@stäbler2022] estime qu'elle est instrumentalisée par les nations de pêche distante. Le manque de gouvernance pourrait même être le résultat de la présence des nations de pêche distante dans une région donnée, avec le concept de criminalité politico-économique [@standing2015].

Enfin plusieurs mécanismes contribuent à instaurer une relation de dépendance des pays détenteurs de ressources vis-à-vis des accords de pêche : dépendance aux revenus générés par l'accord, accord comme prérequis pour obtenir de l'aide au développement [@standing2011], accord nécessaire pour développer le commerce international [@hammarlund2019]. Ceci a contribué à verrouiller un système inégalitaire, dans lequel la pêche industrielle mondiale est dominée par les compagnies des pays du nord [@mccauley2018; @virdin2021; @carmine2020].

## Le cas de l'Afrique de l'Ouest

L'Afrique de l'Ouest est un modèle historique de pêche distante des pays du nord dans une région riche en ressources et peu développée. En effet, la zone Atlantique Centre-Est (zone FAO n°34) est la première zone FAO en termes de captures de pêche distante pendant la seconde moitié du XXe siècle [@bonfil1998]. Elle abrite des eaux parmi les plus productives au monde, divisées en deux large marine ecosystems (LME) : le courant des Canaries (caractérisé par un important système d'upwelling en Mauritanie) et le courant de Guinée; supportant d'important stocks de petits poissons pélagiques et d'espèces démersales.

La pêche distante y existe avant la CNUDM [@bonfil1998; @alder2004; @fao2022] et les conditions sont réunies pour que les pays côtiers de la régions négocient des accords avec les nations de pêche distante une fois leurs ZEE déclarées. En effet, les économies des pays côtiers de la FAO 34 sont peu développées, de même que leurs flottes industrielles domestiques [@bonfil1998]. Ils espèrent alors obtenir des accords plusieurs bénéfices : revenus associés aux licences, augmentation de la capacité de pêche domestique, développement et fourniture de matières premières aux usines de conditionnement locales [@fao2022]. Des autorisations de pêche sont donc négociées sous plusieurs formes [@bonfil1998; @mallory2013; @belhabib2015] : contrats de licence (négociés entre États) ou accords passés entre les compagnies et les gouvernements (firm-to-government). Ces derniers peuvent être de "première génération" avec des prix fixes pour les licences, ou de "seconde génération", basé sur des joint-ventures : associations d'entreprises mêlant capitaux étrangers et domestiques [@fao2022].

La pêche distante dans la région vise principalement les petits poissons pélagiques et les espèces démersales, au chalut [@belhabib2017]. Les flottes de chalutiers sont traditionnellement originaires de l'UE et d'ex-URSS, mais dans les dernières années la flotte chinoise est devenue prédominante [@pauly2014]. Les chalutiers européens opèrent principalement en Mauritanie et en Guinée-Bissau dans le cadre d'accords passés entre gouvernements, tandis que le reste opère dans l'ensemble de la région via des accords passés firm-to-government [@fao2022].

Le contexte socio-économique et politique de la région est par ailleurs propre à favoriser les effets négatifs de la pêche distante. D'une part, les pays côtiers de l'Atlantique Centre-Est sont parmi les plus pauvres au monde, endettés, et instables politiquement, renforçant leur dépendance aux revenus à court terme générés par les accords et diminuant donc leur pouvoir de négociation. D'autre part la corruption systémique et la faible gouvernance des pêches y favorisent des autorisations opaques, économiquement sous-optimales et écologiquement insoutenables [@stäbler2022; @standing2015; @virdin2019; @akpalu2021]. En conséquence, le chalutage étranger est associé à d'importants impacts écologiques et sociaux [@akpalu2021], ou encore à la pêche INN [@belhabib2020; @mpaono2019]. Ces impacts sont d'autant plus marqués qu'une part importante de la population locale dépend de l'activité de pêche artisanale comme moyen de subsistance ou comme source de nourriture bon marché [@fao2024]. Les effets sont considérables, entraînant l'appauvrissement des communautés côtières et la migration des pêcheurs artisans, sources à leur tour de tensions économiques et de conflits [@dème2024].

## Information et responsabilité : les bases de la transparence dans les pêcheries distantes

Face aux conséquences néfastes et à des bénéfices moins élevés qu'anticipé, les pays côtiers cherchent à mieux contrôler la pêche étrangère.

Cette démarche se heurte à plusieurs obstacles, dont le manque de transparence dans la gouvernance des pêches [@guggisberg2022]. Skerritt [-@skerritt2024] a développé un cadre conceptuel identifiant et hiérarchisant six composantes clés de la transparence des pêcheries. Deux éléments sont considérés comme les bases permettant l'obtention des résultats d'une politique des pêche transparente (décisions ouvertes, participation, mise en application et efficacité) : l'information et la capacité à tenir les acteurs pour responsables.

### Sources d'information

A partir de 1950, la collecte de données par la Food and Agriculture Organization (FAO) sur les pêcheries mondiales représente le principal effort institutionnel international pour la diffusion d'information sur la pêche industrielle. Cependant, ces données sont dépendantes du reporting des états de pavillon, dont la qualité comme l'étendue varie grandement, autant entre États que d'une année sur l'autre. Le projet Sea Around Us (SAU) remédie à plusieurs lacunes dans les données déclarées par la FAO au nom des états en reconstituant les captures non déclarées à l'aide de sources de données complémentaires et d'expertise locale afin d'étendre et d'harmoniser les données officielles déclarées. Ce processus de reconstruction des données sur les captures permet également aux données de Sea Around Us de séparer les pêches industrielles de grande envergure des pêches artisanales, de subsistance et récréatives relativement locales [@chuenpagdee2006; @pauly2016; @pauly2016a].

Les applications récentes des données de l’Automatic Identification System (AIS) pour suivre les trajectoires des navires de pêche ont révolutionné l'étude de l'effort de pêche industriel mondial. Initialement développée pour sécuriser le trafic maritime, la technologie AIS consiste en des émissions fréquentes de l'identité et du positionnement GPS (entre autres informations) par un émetteur radio embarqué sur le navire. Cet équipement est obligatoire pour les navires de plus de 300 GT en déplacement international [@internat1974; @revised2015]. En comparant le nombre de navires de pêche émettant par AIS avec les statistiques de la flotte mondiale compilée par la FAO, Taconet et al. [-@taconet2019] estiment que la technologie couvre jusqu'à 84 % des navires de plus de 24 m et 19 % des 12-24 m en 2017. Malgré un fort taux d'augmentation de la couverture ces dernières années (+10 à +30 % de navires détectés entre 2014 et 2017), le suivi par AIS reste consacré à la surveillance de la pêche industrielle. Kroodsma et al. [-@kroodsma2018] ont développé des méthodes d'analyses des trajectoires AIS permettant d'inférer entre autres le type d'engin et les évènements de pêche des navires. La plateforme Global Fishing Watch (GFW) constitue désormais une source majeur d'informations sur l'effort de pêche industriel et et le suivi de la pêche INN à l'échelle mondiale [@taconet2019; @mccauley2018; @tickler2018; @park2023]. Elle a déjà été exploitée avec succès pour étudier la pêche distante en Afrique [@belhabib2020; @li2021; @cappa2024].

### Propriété des navires : la clé de la responsabilité

Si de telles initiatives permettent une diffusion inédite de l'information concernant les impacts des pêcheries distantes, Kinds et al. [-@kinds2025] remarquent que la majorité des études qui traitent du sujet sont conduites à l'échelle des pavillons, i.e. agrégées par états d'immatriculation des navires. Cette approche présente d'importantes limites vis-à-vis de l'attribution des responsabilités puisque les navires sont opérés par des compagnies privées [@carmine2020; @fao2022] avec un rôle important de quelques grandes compagnies transnationales [@österblom2015; @virdin2021] dont Standing [-@standing2015] estime que la pêche INN fait partie intégrante de leur stratégie.

Identifier les propriétaires ultimes des compagnies de pêche est difficile à cause de structures souvent opaques et complexes avec un grand nombre de filiales [@carmine2020; @griggs2007]. Les grandes compagnies de pêche utilisent plusieurs stratégies pour contourner les régulations et maximiser leurs profits : pavillons de complaisance et "reflagging" (changement de pavillon) fréquent [@park2023], paradis fiscaux et sociétés écrans [@galaz2018], liens étroits avec les décideurs politiques [@standing2015] ou encore joint-ventures [@garcía-del-hoyo2021]. Sur ce dernier point la FAO [-@fao2022] insiste, dans le cas particulier de l'Afrique de l'Ouest, sur l'émergence de plus en plus de "fausses joint-ventures" à mesure que les pays côtiers cherchent à restreindre l'accès à leurs ressources naturels aux opérateurs nationaux. Dans ces accords d'accès de seconde génération, le partenaire Africain fait office de prête-nom. Une faible part de capitaux nationaux sont engagés, et l'entreprise peut alors pêcher sans restriction. Ce phénomène est par exemple si fréquent parmi les chalutiers chinois d'Abidjan qu'on parle d'"ivoirisation" des navires.

## Objectifs

On se propose tout d'abord d'actualiser les connaissances sur les caractéristiques de la pêche industrielle en Atlantique Centre-Est. A l'aide des données basées sur la technologie AIS fournies par Global Fishing Watch, la distribution de la capacité et de l'effort de pêche seront analysées. On cherchera à comparer les secteurs industriels domestiques et distants, puis à identifier les principaux acteurs (pavillons et types d'engin). Les données de captures reconstruites du Sea Around Us seront ensuite analysées et comparées avec les évaluations des stocks disponibles pour estimer le niveau de surpêche associé à la pêche distante.

Dans un second temps, une analyse de la propriété des navires opérants dans la zone sera proposée, inspirée de la méthodologie de @kinds2025.

En troisième partie on se concentrera sur la flotte de chalutiers opérants dans la zone FAO 34. Son impact sur l'abrasion des fonds marins et les comportements de pêche INN dans les eaux territoriales des États côtiers seront étudiés suivant des méthodes existantes [@belhabib2020; @eigaard2017] . Dans un objectif d'attribution des responsabilités, les métriques d'impacts calculées seront ensuite agrégées par entités propriétaires des navires (compagnies et états d'enregistrement de celles-ci).
