project:
  type: website

website:
  title: "Distant water fishing in western Africa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 0-data_preparation.qmd
        text: Preprocessing
      #- href: 1-production_resultats.qmd
      #  text: Production
      #- href: 2-manuscript
      #  text: Manuscript

project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



