project:
  type: manuscript

execute:
  freeze: true

manuscript:
  article: 2-manuscript.qmd
  notebooks:
    - notebook: progress.qmd
      title: Paper progress tracking
    - notebook: 0-data_preparation.qmd
      title: Data Preprocessing

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default

crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure



